services:
  db:
    build: ./docker/mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: prototype
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: "./docker/mysql/conf.d"
        target: "/etc/mysql/conf.d"
      - type: bind
        source: "./docker/mysql/initdb.d"
        target: "/docker-entrypoint-initdb.d"
